Skipping unwanted behaviour

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -32,14 +32,14 @@ runs:
   # Checks that all Terraform configuration files adhere to a canonical format
     - name: Terraform Format
       id: check_formatting
-      run: terraform fmt -check  
+      run: terraform fmt  
       continue-on-error: true  
       shell: bash
 
-    - name: Terraform Format Status
-      if: steps.check_formatting.outcome != 'success'
-      run: echo "Formatting error. Please run terraform fmt before pushing your code."; exit 1
-      shell: bash
+    # - name: Terraform Format Status
+    #   if: steps.check_formatting.outcome != 'success'
+    #   run: echo "Formatting error. Please run terraform fmt before pushing your code."; exit 1
+    #   shell: bash
 
   # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
