Terraform action (#12)
* echo added

* shell added

* test

* print

* 'print'

* test

* echo

* test

* print

* test

* test

* test

* test

* test

* test

* test

* print

* test

* test

* test

* test

* test

* test

* plan only removed

* Error message will be displayed if the terrform code has not been formatted

* fixed error to enable shell commands

* Error message will be displayed if the terrform code has not been formatted

* exit after displaying error message

* exit after displaying error message

* Error message will be displayed if the terrform code has not been formatted

* exit after displaying error message

* exit after displaying error message

* exit after displaying error message

* Error message will be displayed if the terrform code has not been formatted

* Error message will be displayed if the terrform code has not been formatted

* echo status code for terraform fmt

* echo status code for terraform fmt

* Annded new step to check status of terraform fmt

* sheell added

* exit of terraform fmt fails

* terminate workflow if formatting fails

* pulling updated code

* Update action.yml

Co-authored-by: Stuart Stone <10559951+stonest@users.noreply.github.com>

* 2 steps merged to one

Co-authored-by: Stuart Stone <10559951+stonest@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,4 +1,4 @@
-name: Terraform AWS Action
+name: Terraform AWS Action 
 
 inputs:
   backend_config:
@@ -53,7 +53,14 @@ runs:
 
   # Checks that all Terraform configuration files adhere to a canonical format
     - name: Terraform Format
-      run: terraform fmt -check
+      id: check_formating
+      run: terraform fmt -check  
+      continue-on-error: true  
+      shell: bash
+
+    - name: Terraform Format Status
+      if: steps.check_formating.outcome != 'success'
+      run: echo "Formatting error. Please run terraform fmt before pushing your code."; exit 1
       shell: bash
 
   # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
