Update action.yml
Co-authored-by: Stuart Stone <10559951+stonest@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -60,7 +60,7 @@ runs:
 
     - name: Terraform Format Status
       if: steps.check_formating.outcome != 'success'
-      run: echo "Formatting error. Please run terraform fmt before pushing your code."
+      run: echo "Formatting error. Please run terraform fmt before pushing your code."; exit 1
       shell: bash
 
     - name: Terraform Format Status Failure
